[stack]
id = "heroku-20"
build-image = "heroku/pack:20-build"
run-image = "heroku/pack:20"

[lifecycle]
version = "0.10.1"

[[buildpacks]]
  id = "heroku/maven"
  uri = "docker://public.ecr.aws/r2f9u0w4/heroku-maven-buildpack:0.2.0"

[[buildpacks]]
  id = "heroku/jvm"
  uri = "docker://public.ecr.aws/r2f9u0w4/heroku-jvm-buildpack:0.1.2"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://public.ecr.aws/r2f9u0w4/heroku-java-buildpack:0.1.3"

[[buildpacks]]
  id = "heroku/gradle"
  uri = "docker://public.ecr.aws/r2f9u0w4/heroku-gradle-buildpack:0.0.34"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://public.ecr.aws/r2f9u0w4/heroku-scala-buildpack:0.0.88"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "https://github.com/heroku/heroku-buildpack-ruby/releases/download/v222/heroku-buildpack-ruby-v222.tgz"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:0.6.1"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.3&name=Python"

[[buildpacks]]
  id = "heroku/php"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php?version=0.3&name=PHP"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.3&name=Go"

[[buildpacks]]
  id = "heroku/nodejs-engine"
  uri = "https://github.com/heroku/nodejs-engine-buildpack/releases/download/v0.7.0/nodejs-engine-buildpack-v0.7.0.tgz"

[[buildpacks]]
  id = "heroku/nodejs-npm"
  uri = "https://github.com/heroku/nodejs-npm-buildpack/releases/download/v0.4.0/nodejs-npm-buildpack-v0.4.0.tgz"

[[buildpacks]]
  id = "heroku/nodejs-yarn"
  uri = "https://github.com/heroku/nodejs-yarn-buildpack/releases/download/v0.1.0/nodejs-yarn-buildpack-v0.1.0.tgz"

[[buildpacks]]
  id = "heroku/nodejs-typescript"
  uri = "https://github.com/heroku/nodejs-typescript-buildpack/releases/download/v0.2.0/nodejs-typescript-buildpack-v0.2.0.tgz"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "buildpacks/heroku_nodejs"

[[buildpacks]]
  id = "salesforce/nodejs-fn"
  uri = "https://github.com/forcedotcom/nodejs-sf-fx-buildpack/releases/download/v2.0.5/nodejs-sf-fx-buildpack-v2.0.5.tgz"

[[buildpacks]]
  id = "projectriff/streaming-http-adapter"
  uri = "docker://gcr.io/projectriff/streaming-http-adapter:1.4.0"

[[buildpacks]]
  id = "projectriff/node-function"
  uri = "docker://gcr.io/projectriff/node-function:1.5.0"

[[buildpacks]]
  id = "evergreen/fn"
  uri = "buildpacks/evergreen_fn"

[[order]]
  [[order.group]]
    id = "heroku/ruby"

  [[order.group]]
    id = "heroku/procfile"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"

  [[order.group]]
    id = "heroku/procfile"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/java"

[[order]]
  [[order.group]]
    id = "heroku/scala"

  [[order.group]]
    id = "heroku/procfile"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"

  [[order.group]]
    id = "heroku/procfile"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"

  [[order.group]]
    id = "heroku/procfile"
    optional = true

[[order]]
  [[order.group]]
    id = "evergreen/fn"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
