[stack]
id = "heroku-18"
build-image = "heroku/pack:18-build"
run-image = "heroku/pack:18"

[lifecycle]
version = "0.6.1"

[[buildpacks]]
  id = "heroku/nodejs-engine"
  uri = "https://github.com/heroku/nodejs-engine-buildpack/releases/download/v0.4.3/nodejs-engine-buildpack-v0.4.3.tgz"

[[buildpacks]]
  id = "heroku/nodejs-npm"
  uri = "https://github.com/heroku/nodejs-npm-buildpack/releases/download/v0.2.0/nodejs-npm-buildpack-v0.2.0.tgz"

[[buildpacks]]
  id = "salesforce/nodejs-fn"
  uri = "https://github.com/forcedotcom/nodejs-sf-fx-buildpack/releases/download/v1.4.1/nodejs-sf-fx-buildpack-v1.4.1.tgz"

[[buildpacks]]
  id = "heroku/node-function"
  uri = "https://github.com/heroku/node-function-buildpack/releases/download/v0.7.0/node-function-buildpack-v0.7.0.tgz"

[[buildpacks]]
  id = "heroku/maven"
  uri = "https://github.com/heroku/heroku-buildpack-java/releases/download/cnb/heroku-buildpack-maven.tgz"

[[buildpacks]]
  id = "heroku/jvm"
  uri = "https://github.com/heroku/heroku-buildpack-jvm-common/releases/download/v96/heroku-jvm-cnb.tgz"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "https://github.com/heroku/java-function-buildpack/releases/download/v0.3.0/java-function-buildpack-v0.3.0.tgz"

[[order]]
  # node functions
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "0.4.3"

  [[order.group]]
    id = "heroku/nodejs-npm"
    version = "0.2.0"

  [[order.group]]
    id = "salesforce/nodejs-fn"
    version = "1.4.1"

  [[order.group]]
    id = "heroku/node-function"
    version = "0.7.0"

[[order]]
  # java functions
  [[order.group]]
    id = "heroku/jvm"
    version = "0.1"

  [[order.group]]
    id = "heroku/maven"
    version = "0.1"

  [[order.group]]
    id = "heroku/java-function"
    version = "0.3.0"
