[stack]
id = "heroku-18"
build-image = "heroku/pack:18-build"
run-image = "heroku/pack:18"

[lifecycle]
version = "0.9.2"

[[buildpacks]]
  id = "heroku/jvm"
  uri = "https://github.com/heroku/heroku-buildpack-jvm-common/releases/download/v111/heroku-jvm-common-cnb-v111.tgz"

[[buildpacks]]
  id = "heroku/spring-boot"
  uri = "urn:cnb:registry:heroku/spring-boot@0.2.2"

[[order]]
  [[order.group]]
    id = "heroku/jvm"

  [[order.group]]
    id = "heroku/spring-boot"
