description = "Classic (shimmed) buildpack builder for Heroku-22 stack, based on ubuntu:22.04 base image"

[stack]
id = "heroku-22"
build-image = "heroku/heroku:22-cnb-build"
run-image = "heroku/heroku:22-cnb"

[lifecycle]
version = "0.14.0"

[[buildpacks]]
  id = "heroku/clojure-classic"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/clojure?version=0.3.1&name=Clojure"

[[buildpacks]]
  id = "heroku/gradle-classic"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/gradle?version=0.3.1&name=Gradle"

[[buildpacks]]
  id = "heroku/java-classic"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/java?version=0.3.1&name=Java"

[[buildpacks]]
  id = "heroku/go-classic"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.3.1&name=Go"

[[buildpacks]]
  id = "heroku/nodejs-classic"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/nodejs?version=0.3.1&name=Node.js"

[[buildpacks]]
  id = "heroku/php-classic"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php?version=0.3.1&name=PHP"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:1.0.1"

[[buildpacks]]
  id = "heroku/python-classic"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.3.1&name=Python"

[[buildpacks]]
  id = "heroku/ruby-classic"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/ruby?version=0.3.1&name=Ruby"

[[buildpacks]]
  id = "heroku/scala-classic"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/scala?version=0.3.1&name=Scala"

[[order]]
  [[order.group]]
    id = "heroku/ruby-classic"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/clojure-classic"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python-classic"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/java-classic"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/gradle-classic"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala-classic"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php-classic"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go-classic"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true
