version: 2.0
jobs:
  clone:
    machine: true
    steps:
      - checkout
      - save-cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project
  docker-prep:
    machine: true
    steps:
      - run: echo {} > ~/.docker/config.json
      - run: docker pull heroku/heroku:18-build
      - run: docker pull heroku/heroku:18
  install-buildpacks:
    machine: true
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: pwd; ls
      - run: ./buildpacks/install.sh
      - save-cache:
          key: v1-buildpacks-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project/buildpacks
  docker-build-run-image:
    machine: true
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-buildpacks-{{ .Environment.CIRCLE_SHA1 }}
      - run: docker build -f Dockerfile.run -t heroku/pack:18-test .
  docker-build-build-image:
    machine: true
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-buildpacks-{{ .Environment.CIRCLE_SHA1 }}
      - run: docker build -f Dockerfile.build -t heroku/pack:18-build-test .
  create-builder-image:
    machine: true
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-buildpacks-{{ .Environment.CIRCLE_SHA1 }}
      - run: go get github.com/buildpack/pack/cmd/pack
      - run: pack create-builder heroku/buildpacks:18-test --builder-config builder.toml --no-pull
  test-go:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: git clone git@github.com:heroku/go-getting-started
      - run: pack build heroku/go-getting-started:test --path go-getting-started --builder heroku/buildpacks:18-test
workflows:
  version: 2
  test-languages:
    jobs:
      - clone
      - docker-prep
      - install-buildpacks:
          requires: 
            - clone
      - docker-build-run-image:
          requires:
            - docker-prep
      - docker-build-build-image:
          requires:
            - docker-prep
      - create-builder-image:
          requires:
            - install-buildpacks
            - docker-build-run-image
            - docker-build-build-image
      - test-go:
          requires: 
            - create-builder-image
