version: 2.1
jobs:
  clone:
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project
  install-buildpacks:
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: ./buildpacks/install.sh
      - save_cache:
          key: v1-buildpacks-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project/buildpacks
  create-image:
    parameters:
      dockerfile:
        description: "Dockerfile to build"
        type: string
      image_file:
        description: "Local image archive file name"
        type: string
      image_tag:
        description: "Remote image tag name"
        type: string
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-buildpacks-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run: docker build -f << parameters.dockerfile >> -t << parameters.image_tag >> .
      - run: docker save << parameters.image_tag >> > << parameters.image_file >>
      - save_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-<< parameters.image_file >>
          paths:
            - << parameters.image_file >>
  create-pack-builder:
    parameters:
      builder_toml:
        description: "Builder toml"
        type: string
      image_file:
        description: "Local builder image archive file name"
        type: string
      image_tag:
        description: "Remote builder image name"
        type: string
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-buildpacks-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-pack-18-build.tar
      - restore_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-pack-18-run.tar
      - setup_remote_docker
      - run: docker load < pack-18-build.tar
      - run: docker load < pack-18-run.tar
      - run: pack create-builder << parameters.image_tag >> --builder-config << parameters.builder_toml >> --no-pull
      - run: docker save << parameters.image_tag >> > << parameters.image_file >>
      - save_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-<< parameters.image_file >>
          paths:
            - << parameters.image_file >>
  test-getting-started-guide:
    parameters:
      language:
        description: "Language"
        type: string
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - run: git clone https://github.com/heroku/<< parameters.language >>-getting-started.git getting_started
      - setup_remote_docker
      - restore_cache:
          key: v1-docker-cache-pack-18-build-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-docker-cache-pack-18-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-docker-cache-buildpacks-18-{{ .Environment.CIRCLE_SHA1 }}
      - run: docker load < docker_cache_build_pack-18-build/pack-18-build.tar
      - run: docker load < docker_cache_run_pack-18/pack-18.tar
      - run: docker load < docker_cache_buildpacks-18/buildpacks-18.tar
      - run: pack build pack-getting-started --path getting_started --builder buildpacks-18 --no-pull
  publish-image:
    parameters:
      local_image:
        description: "Name of the local image to publish"
        type: string
      remote_image:
        description: "Name of the dockerhub image to publish"
        type: string
      remote_image_alias:
        description: "Name of dockerhub image alias to publish"
        type: string
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - setup_remote_docker
      - run: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
      - restore_cache:
          key: v1-docker-cache-<< parameters.local_image >>-{{ .Environment.CIRCLE_SHA1 }}
      - run: docker load < docker_cache_<< parameters.local_image >>/<< parameters.local_image >>.tar
      - run: docker tag << parameters.local_image >> << parameters.remote_image >>
      - run: docker tag << parameters.local_image >> << parameters.remote_image_alias >>
      - run: docker push << parameters.remote_image >>
      - run: docker push << parameters.remote_image_alias >>
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - clone
      - install-buildpacks:
          requires:
            - clone
      - create-image:
          name: create-build-image
          dockerfile: Dockerfile.build
          image_tag: pack:18-build
          image_file: pack-18-build.tar
          requires:
            - clone
      - create-image:
          name: create-run-image
          dockerfile: Dockerfile.run
          image_tag: pack:18
          image_file: pack-18-run.tar
          requires:
            - clone
      - create-pack-builder:
          name: create-service-builder
          image_tag: heroku/buildpacks:18
          image_file: buildpacks-18.tar
          builder_toml: builder.toml
          requires:
            - install-buildpacks
            - create-run-image
            - create-build-image
      - create-pack-builder:
          name: create-functions-builder
          image_tag: heroku/functions-buildpacks:18
          image_file: functions-buildpacks-18.tar
          builder_toml: functions-builder.toml
          requires:
            - install-buildpacks
            - create-run-image
            - create-build-image
      - test-getting-started-guide:
          language: go
          name: test-go
          requires:
            - create-service-builder
      - test-getting-started-guide:
          language: java
          name: test-java
          requires:
            - create-service-builder
      - test-getting-started-guide:
          language: node-js
          name: test-node-js
          requires:
            - create-service-builder
      - test-getting-started-guide:
          language: php
          name: test-php
          requires:
            - create-service-builder
      - test-getting-started-guide:
          language: Python
          name: test-python
          requires:
            - create-service-builder
      - test-getting-started-guide:
          language: Ruby
          name: test-ruby
          requires:
            - create-service-builder
      - publish-image:
          name: publish-service-builder
          local_image: buildpacks-18
          remote_image: heroku/buildpacks:18
          remote_image_alias: heroku/buildpacks:latest
          requires:
            - test-go
            - test-java
            - test-node-js
            - test-php
            - test-python
            - test-ruby
      - publish-image:
          name: publish-functions-builder
          local_image: functions-buildpacks-18
          remote_image: heroku/functions-buildpacks:18
          remote_image_alias: heroku/functions-buildpacks:latest
          requires:
            - create-functions-builder
            - test-go
            - test-java
            - test-node-js
            - test-php
            - test-python
            - test-ruby
