version: 2.1
jobs:
  clone:
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project
  install-buildpacks:
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: ./buildpacks/install.sh
      - save_cache:
          key: v1-buildpacks-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project/buildpacks
  create-run-image:
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-buildpacks-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run: docker build -f Dockerfile.run -t heroku/pack:18 .
      - run: mkdir docker_cache_run_base
      - run: docker save heroku/pack:18 > docker_cache_run_base/pack-18.tar
      - save_cache:
          key: v1-docker-cache-run-base-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - docker_cache_run_base
  create-build-image:
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-buildpacks-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run: docker build -f Dockerfile.build -t heroku/pack:18-build .
      - run: mkdir docker_cache_build_base
      - run: docker save heroku/pack:18-build > docker_cache_build_base/pack-18-build.tar
      - save_cache:
          key: v1-docker-cache-build-base-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - docker_cache_build_base
  create-pack-builder:
    parameters:
      buildertoml:
        description: "Builder toml"
        type: string
      imagename:
        description: "Name of the image"
        type: string
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-buildpacks-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-docker-cache-build-base-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-docker-cache-run-base-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run: docker load < docker_cache_build_base/pack-18-build.tar
      - run: docker load < docker_cache_run_base/pack-18.tar
      - run: pack create-builder << parameters.imagename >> --builder-config << parameters.buildertoml >> --no-pull
      - run: mkdir docker_cache_<< parameters.imagename >>
      - run: docker save << parameters.imagename >> > docker_cache_<< parameters.imagename >>/<< parameters.imagename >>.tar
      - save_cache:
          key: v1-docker-cache-<< parameters.imagename >>-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - docker_cache_<< parameters.imagename >>
  test-getting-started-guide:
    parameters:
      language:
        description: "Language"
        type: string
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - run: git clone https://github.com/heroku/<< parameters.language >>-getting-started.git getting_started
      - setup_remote_docker
      - restore_cache:
          key: v1-docker-cache-build-base-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-docker-cache-run-base-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-docker-cache-buildpacks-18-{{ .Environment.CIRCLE_SHA1 }}
      - run: docker load < docker_cache_build_base/pack-18-build.tar
      - run: docker load < docker_cache_run_base/pack-18.tar
      - run: docker load < docker_cache_buildpacks-18/buildpacks-18.tar
      - run: pack build pack-getting-started --path getting_started --builder buildpacks-18 --no-pull
  publish-image:
    parameters:
      local_image:
        description: "Name of the local image to publish"
        type: string
      remote_image:
        description: "Name of the dockerhub image to publish"
        type: string
      remote_image_alias:
        description: "Name of dockerhub image alias to publish"
        type: string
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - setup_remote_docker
      - restore_cache:
          key: v1-docker-cache-<< parameters.local_image >>-{{ .Environment.CIRCLE_SHA1 }}
      - run: docker load < docker_cache_<< parameters.local_image >>/<< parameters.local_image >>.tar
      - run: docker tag << parameters.local_image >> << parameters.remote_image >>
      - run: docker tag << parameters.local_image >> << parameters.remote_image_alias >>
      - run: docker push << parameters.remote_image >>
      - run: docker push << parameters.remote_image_alias >>
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - clone
      - install-buildpacks:
          requires:
            - clone
      - create-run-image:
          requires:
            - clone
      - create-build-image:
          requires:
            - clone
      - create-pack-builder:
          name: create-service-builder
          imagename: buildpacks-18
          buildertoml: builder.toml
          requires:
            - install-buildpacks
            - create-run-image
            - create-build-image
      - create-pack-builder:
          name: create-functions-builder
          imagename: functions-buildpacks-18
          buildertoml: functions-builder.toml
          requires:
            - install-buildpacks
            - create-run-image
            - create-build-image
      - test-getting-started-guide:
          language: go
          name: test-go
          requires:
            - create-service-builder
      - test-getting-started-guide:
          language: java
          name: test-java
          requires:
            - create-service-builder
      - test-getting-started-guide:
          language: node-js
          name: test-node-js
          requires:
            - create-service-builder
      - test-getting-started-guide:
          language: php
          name: test-php
          requires:
            - create-service-builder
      - test-getting-started-guide:
          language: Python
          name: test-python
          requires:
            - create-service-builder
      - test-getting-started-guide:
          language: Ruby
          name: test-ruby
          requires:
            - create-service-builder
      - publish-image:
          name: publish-service-builder
          local_image: buildpacks-18
          remote_image: heroku/buildpacks:18
          remote_image_alias: heroku/buildpacks:latest
          requires:
            - test-go
            - test-java
            - test-node-js
            - test-php
            - test-python
            - test-ruby
      - publish-image:
          name: publish-functions-builder
          local_image: functions-buildpacks-18
          remote_image: heroku/functions-buildpacks:18
          remote_image_alias: heroku/functions-buildpacks:latest
          requires:
            - create-functions-builder
            - test-go
            - test-java
            - test-node-js
            - test-php
            - test-python
            - test-ruby
