version: 2.1
jobs:
  create-image:
    parameters:
      dockerfile:
        description: "Dockerfile to build"
        type: string
      base_image:
        description: "The Docker image to be used in the FROM line of the Dockerfile"
        type: string
      stack_name:
        description: "The name of the stack"
        type: string
      image_file:
        description: "Local image archive file name"
        type: string
      image_tag:
        description: "Remote image tag name"
        type: string
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run: docker build -f << parameters.dockerfile >> --build-arg STACK=<< parameters.stack_name >> --build-arg BASE_IMAGE=<< parameters.base_image >> -t << parameters.image_tag >> .
      - run: docker save << parameters.image_tag >> > /tmp/workspace/<< parameters.image_file >>
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - << parameters.image_file >>
  create-pack-builder:
    parameters:
      builder_toml:
        description: "Builder toml"
        type: string
      image_file:
        description: "Local builder image archive file name"
        type: string
      image_tag:
        description: "Remote builder image name"
        type: string
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: &create-docker-config
          name: "Create docker config"
          command: |
            mkdir -p ~/.docker
            echo '{}' > ~/.docker/config.json
      - run: &install-pack
          name: "Install pack"
          command: |
            wget https://github.com/buildpacks/pack/releases/download/v0.15.1/pack-v0.15.1-linux.tgz
            tar xvf pack-v0.15.1-linux.tgz
            rm pack-v0.15.1-linux.tgz
            mkdir -p ~/bin/
            mv pack $HOME/bin/
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run: docker pull gcr.io/projectriff/streaming-http-adapter:0.1.3
      - run: docker pull gcr.io/projectriff/node-function:0.6.1
      - run: docker load < $(ls /tmp/workspace/pack-*-build.tar | head -1)
      - run: docker load < $(ls /tmp/workspace/pack-*-run.tar | head -1)
      - run: pack create-builder << parameters.image_tag >> --config << parameters.builder_toml >> --pull-policy never
      - run: docker save << parameters.image_tag >> > /tmp/workspace/<< parameters.image_file >>
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - << parameters.image_file >>
  test-getting-started-guide:
    parameters:
      language:
        description: "Language"
        type: string
      stack-tag:
        description: "The tag of the run stack (ex. '20' for heroku/heroku:20)"
        type: string
    docker:
      - image: circleci/golang:1.15
    steps:
      - run: git clone https://github.com/heroku/<< parameters.language >>-getting-started.git getting_started
      - run: *create-docker-config
      - run: *install-pack
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run: docker load < /tmp/workspace/pack-<< parameters.stack-tag >>-build.tar
      - run: docker load < /tmp/workspace/pack-<< parameters.stack-tag >>-run.tar
      - run: docker load < /tmp/workspace/buildpacks-<< parameters.stack-tag >>.tar
      - run: pack trust-builder heroku/buildpacks:<< parameters.stack-tag >>
      - run: pack build pack-getting-started --path getting_started --builder heroku/buildpacks:<< parameters.stack-tag >> --pull-policy never
  test-evergreen-canary:
    parameters:
      url:
        description: "Evergreen canaries github repo"
        type: string
      path:
        description: "Build path"
        type: string
      fingerprint:
        description: "Github private repo SSH key"
        type: string
      builder_image_tag:
        description: "Builder image tag to use"
        type: "string"
      builder_file_name:
        description: "Builder cached image name"
        type: "string"
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: *create-docker-config
      - run: *install-pack
      - add_ssh_keys:
          fingerprints:
            - << parameters.fingerprint >>
      - run: git clone https://github.com/heroku/evergreen-<< parameters.url >>.git evergreen-canary
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run: docker load < /tmp/workspace/pack-18-build.tar
      - run: docker load < /tmp/workspace/pack-18-run.tar
      - run: docker load < /tmp/workspace/<< parameters.builder_file_name >>
      - run: pack build pack-evergreen-canary --path evergreen-canary/src/<< parameters.path >> --builder << parameters.builder_image_tag >> --trust-builder --pull-policy never
  publish-image:
    parameters:
      image_file:
        description: "Name of the local image archive to publish"
        type: string
      image_tag:
        description: "Name of the dockerhub image to publish"
        type: string
      image_tag_alias:
        description: "Name of dockerhub image alias to publish"
        type: string
    docker:
      - image: circleci/golang:1.15
    steps:
      - setup_remote_docker
      - run: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
      - attach_workspace:
          at: /tmp/workspace
      - run: docker load < /tmp/workspace/<< parameters.image_file >>
      - run: docker push << parameters.image_tag >>
      - run: docker tag << parameters.image_tag >> << parameters.image_tag_alias >>
      - run: docker push << parameters.image_tag_alias >>
workflows:
  version: 2
  build-test-publish:
    jobs: &build-test-publish-jobs
      - create-image:
          name: create-18-build-image
          dockerfile: Dockerfile.build
          base_image: heroku/heroku:18-build
          stack_name: heroku-18
          image_tag: heroku/pack:18-build
          image_file: pack-18-build.tar
      - create-image:
          name: create-18-run-image
          dockerfile: Dockerfile.run
          base_image: heroku/heroku:18
          stack_name: heroku-18
          image_tag: heroku/pack:18
          image_file: pack-18-run.tar
      - create-image:
          name: create-20-build-image
          dockerfile: Dockerfile.build
          base_image: heroku/heroku:20-build
          stack_name: heroku-20
          image_tag: heroku/pack:20-build
          image_file: pack-20-build.tar
      - create-image:
          name: create-20-run-image
          dockerfile: Dockerfile.run
          base_image: heroku/heroku:20
          stack_name: heroku-20
          image_tag: heroku/pack:20
          image_file: pack-20-run.tar
      - create-pack-builder:
          name: create-service-builder-18
          image_tag: heroku/buildpacks:18
          image_file: buildpacks-18.tar
          builder_toml: builder-18.toml
          requires:
            - create-18-run-image
            - create-18-build-image
      - create-pack-builder:
          name: create-service-builder-20
          image_tag: heroku/buildpacks:20
          image_file: buildpacks-20.tar
          builder_toml: builder-20.toml
          requires:
            - create-20-run-image
            - create-20-build-image
      - test-getting-started-guide:
          language: go
          stack-tag: "18"
          name: test-go-18
          requires:
            - create-service-builder-18
      - test-getting-started-guide:
          language: go
          stack-tag: "20"
          name: test-go-20
          requires:
            - create-service-builder-20
      - test-getting-started-guide:
          language: java
          stack-tag: "18"
          name: test-java-18
          requires:
            - create-service-builder-18
      - test-getting-started-guide:
          language: java
          stack-tag: "20"
          name: test-java-20
          requires:
            - create-service-builder-20
      - test-getting-started-guide:
          language: node-js
          stack-tag: "18"
          name: test-node-js-18
          requires:
            - create-service-builder-18
      - test-getting-started-guide:
          language: typescript
          stack-tag: "18"
          name: test-typescript-18
          requires:
            - create-service-builder-18
      - test-getting-started-guide:
          language: php
          stack-tag: "18"
          name: test-php-18
          requires:
            - create-service-builder-18
      - test-getting-started-guide:
          language: php
          stack-tag: "20"
          name: test-php-20
          requires:
            - create-service-builder-20
      - test-getting-started-guide:
          language: Python
          stack-tag: "18"
          name: test-python-18
          requires:
            - create-service-builder-18
      - test-getting-started-guide:
          language: Python
          stack-tag: "20"
          name: test-python-20
          requires:
            - create-service-builder-20
      - test-getting-started-guide:
          language: Ruby
          stack-tag: "18"
          name: test-ruby-18
          requires:
            - create-service-builder-18
      - test-getting-started-guide:
          language: Ruby
          stack-tag: "20"
          name: test-ruby-20
          requires:
            - create-service-builder-20
      - test-evergreen-canary:
          name: test-canary-https-invocation-builder
          url: canary-https-invocation
          path: hello-function
          fingerprint: "5f:51:54:de:aa:c6:91:98:3e:e9:b2:a3:94:e7:05:6d"
          builder_image_tag: "heroku/buildpacks:18"
          builder_file_name: buildpacks-18.tar
          requires:
            - create-service-builder-18
      - test-evergreen-canary:
          name: test-canary-logs-cli-builder
          url: canary-logs-cli
          path: salesforce/functions/ExampleFunction
          fingerprint: "c1:1d:be:7b:33:56:47:56:8a:84:55:15:9f:7c:5e:1c"
          builder_image_tag: "heroku/buildpacks:18"
          builder_file_name: buildpacks-18.tar
          requires:
            - create-service-builder-18
      - publish-image:
          name: publish-18-build-stack
          image_file: pack-18-build.tar
          image_tag: heroku/pack:18-build
          image_tag_alias: heroku/pack:18-build
          requires:
            - test-go-18
            - test-java-18
            - test-node-js-18
            - test-ruby-18
            - test-php-18
            - test-python-18
            - test-canary-https-invocation-builder
            - test-canary-logs-cli-builder
          filters:
            branches:
              only: master
      - publish-image:
          name: publish-18-run-stack
          image_file: pack-18-run.tar
          image_tag: heroku/pack:18
          image_tag_alias: heroku/pack:18
          requires:
            - test-go-18
            - test-java-18
            - test-node-js-18
            - test-ruby-18
            - test-php-18
            - test-python-18
            - test-canary-https-invocation-builder
            - test-canary-logs-cli-builder
          filters:
            branches:
              only: master
      - publish-image:
          name: publish-service-builder-18
          image_file: buildpacks-18.tar
          image_tag: heroku/buildpacks:18
          image_tag_alias: heroku/buildpacks:latest
          requires:
            - publish-18-build-stack
            - publish-18-run-stack
          filters:
            branches:
              only: master
      - publish-image:
          name: publish-20-build-stack
          image_file: pack-20-build.tar
          image_tag: heroku/pack:20-build
          image_tag_alias: heroku/pack:20-build
          requires:
            - test-go-20
            - test-ruby-20
            - test-java-20
            - test-php-20
            - test-python-20
          filters:
            branches:
              only: master
      - publish-image:
          name: publish-20-run-stack
          image_file: pack-20-run.tar
          image_tag: heroku/pack:20
          image_tag_alias: heroku/pack:20
          requires:
            - test-go-20
            - test-ruby-20
            - test-java-20
            - test-php-20
            - test-python-20
          filters:
            branches:
              only: master
      - publish-image:
          name: publish-service-builder-20
          image_file: buildpacks-20.tar
          image_tag: heroku/buildpacks:20
          image_tag_alias: heroku/buildpacks:20
          requires:
            - publish-20-build-stack
            - publish-20-run-stack
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs: *build-test-publish-jobs
