api = "0.2"

[buildpack]
id = "heroku/nodejs"
version = "0.1"
name = "Node.js"

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "0.7.0"

  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "0.1.0"

  [[order.group]]
    id = "heroku/nodejs-typescript"
    version = "0.2.0"
    optional = true

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "0.7.0"

  [[order.group]]
    id = "heroku/nodejs-npm"
    version = "0.4.0"

  [[order.group]]
    id = "heroku/nodejs-typescript"
    version = "0.2.0"
    optional = true

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6"
    optional = true

