description = "Heroku-20 (Ubuntu 20.04) base image with buildpacks for Go, Java, Node.js, PHP, Python, Ruby & Scala."

[stack]
id = "heroku-20"
build-image = "heroku/heroku:20-cnb-build"
run-image = "heroku/heroku:20-cnb"

[lifecycle]
version = "0.19.0"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:8123cbeefc05f54c0f4b386bccdc78710d55bc500a99d6b75afd0680d537e016"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:20b9b71a87e94e82d2e3a54e9329af49bce93d61211e4169cfe7b490972cf8d0"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:643a4e4b95099b80f42e06fbdbbfb54b79c53989109510990a6085e41dd3862e"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:9d76792ba9869eb96ba3b41b0bfb48c6adfaa58a361bba6083505c84c5a8d61e"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/buildpack-procfile@sha256:1995d5e70d12b928172a09b11ab7b0c07da7857588e743b0e55d4be0d1a59fbf"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:34032be4bec62970479c97c57ad25f41960460191461bc8b244cd0d35811fbb6"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:b82d0a0d59dd97615fe082e4e31c3af25790dd88a0c5c6b8d553504f6b22526b"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:dcf51d14112e5b97cf2f7e1cd19dd89e4850762080dc29c80623c02413ca6e6f"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.8.2"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "3.0.1"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "3.0.1"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "4.1.0"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "2.1.2"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "3.0.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "4.1.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "4.1.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.2.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.1.2"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true
