description = "[DEPRECATED] Ubuntu 20.04 AMD64 base image with buildpacks for Go, Java, Node.js, PHP, Python, Ruby & Scala."

[stack]
id = "heroku-20"
build-image = "docker.io/heroku/heroku:20-cnb-build"
run-image = "docker.io/heroku/heroku:20-cnb"
run-image-mirrors = ["public.ecr.aws/heroku/heroku:20-cnb"]

[build]
image = "docker.io/heroku/heroku:20-cnb-build"

[run]
[[run.images]]
image = "docker.io/heroku/heroku:20-cnb"
mirrors = ["public.ecr.aws/heroku/heroku:20-cnb"]

[lifecycle]
version = "0.20.2"

[[buildpacks]]
  id = "heroku/eol-warning"
  uri = "./eol-buildpack/"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:71c346d575a62fd427e906122f0145ba7ba3d7dec679f68f4fb3bc2e0e4a1fa1"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:16e222b2343151eebb7b52f018d94371a444bd9adeb99f32ee4b2af46e9f2578"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:f6fc41acaae63c8bf935e1e52d4d0e5f18481f19834fd01f3e4b89be93e13054"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:21c6e7c49c6a62167ff1f8c2d1aaebdde99e278d677ecb04ec404a1f66065d93"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/buildpack-procfile@sha256:2e57b342cab83f6517bb1b94f7ebedd2f9b723b8dc7536c15009a779ef2df92f"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:c02de288939ed611a31a0a12090dbf2c55e72d6316572c056936883ca0d465e6"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:b98b873adf2fc51dce9ae09331486cfe2f799ec233eb7128d1f5068e6e63e25a"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:6b5419aee9f1715c9f193074fabe7e3671bb68c56f13b772a87cafae36b80405"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.18.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "3.2.14"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "3.2.14"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "6.0.3"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "3.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "3.2.14"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "6.0.3"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "6.0.3"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.4.5"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.2.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"
