description = "[DEPRECATED] Ubuntu 20.04 AMD64 base image with buildpacks for Go, Java, Node.js, PHP, Python, Ruby & Scala."

[stack]
id = "heroku-20"
build-image = "docker.io/heroku/heroku:20-cnb-build"
run-image = "docker.io/heroku/heroku:20-cnb"
run-image-mirrors = ["public.ecr.aws/heroku/heroku:20-cnb"]

[build]
image = "docker.io/heroku/heroku:20-cnb-build"

[run]
[[run.images]]
image = "docker.io/heroku/heroku:20-cnb"
mirrors = ["public.ecr.aws/heroku/heroku:20-cnb"]

[lifecycle]
version = "0.20.5"

[[buildpacks]]
  id = "heroku/eol-warning"
  uri = "./eol-buildpack/"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:0ee87ed2bd917e75e830f137524460682dd7f8543bf8d85a2e59be0a1b1c945e"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:d0fb1b34b7b02276cf3b265b498ee1eaf7be3bf84511c7f1b9bc231820440292"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:ed81695864d787ea20cab4ef6dc2a6e4626bedca3b4fb77d0f820020280e13bd"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:21c6e7c49c6a62167ff1f8c2d1aaebdde99e278d677ecb04ec404a1f66065d93"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/buildpack-procfile@sha256:78bbdb96dacbd50441be49c051b633b39b58e1bc1465af613cf099eca2cb1693"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:c68ee55eafa01355964e2568fc36fe17696c2e6ae40d5964ae56959f79da0a68"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:4647996e0a8e7c37c79d0c1e0b9f049d1f23e5ac0be65e13adff95f33cea5efa"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:52a5e80f06f7a312cf619eb14b091adbdb56af9ec19ffab366952faa872fef7f"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.22.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.2.0"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "3.4.2"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "3.4.2"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "6.0.4"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "5.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.2.0"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "6.0.4"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.2.0"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "6.0.4"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.2.0"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.5.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.2.0"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.2.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.2.0"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"

# this group is intentionally at the end, because projects in other languages often have e.g. a package.json
[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "3.4.2"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.2.0"
    optional = true
  [[order.group]]
    id = "heroku/eol-warning"
    version = "1.0.0"
