description = "Heroku-20 (Ubuntu 20.04) base image with buildpacks for Go, Java, Node.js, PHP, Python, Ruby & Scala."

[stack]
id = "heroku-20"
build-image = "heroku/heroku:20-cnb-build"
run-image = "heroku/heroku:20-cnb"

[lifecycle]
version = "0.19.3"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:6e6957d6118b6c3cb39b9217587acc1de8616181aeccf6eb1af2b218ffb60e0d"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:b8a2ececd099a9e566207ccb376ed63212a08d2598c574992eba7b0e6782a9f0"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:baea2da923e39ac90f308ccea96ac174b056fd27eff7ddca67d60363b55f8f61"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:9d76792ba9869eb96ba3b41b0bfb48c6adfaa58a361bba6083505c84c5a8d61e"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/buildpack-procfile@sha256:2de0917544af55f26631a5a9e3f812b1da6c05067abfd75dc9a87a1da7172586"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:7c9764d4c30c038ab52e10075a9ac3d05b17be28679eb2c3309156be8a0ef84a"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:995e2898a7a7fe1cb38ac24263d2f7d3fba1051ce170033320116a8aa81f9b21"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:ad3e19d986e9306938f6e83b0a8ffafa84ca9277f64d748c4f50eef62af14f37"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.8.4"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "3.0.5"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "3.0.5"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "4.1.1"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "2.1.3"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "3.0.5"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "4.1.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "4.1.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.2.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.1.2"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true
