description = "Heroku-20 (Ubuntu 20.04) base image with buildpacks for Go, Java, Node.js, PHP, Python, Ruby & Scala."

[stack]
id = "heroku-20"
build-image = "heroku/heroku:20-cnb-build"
run-image = "heroku/heroku:20-cnb"

[lifecycle]
version = "0.19.3"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:6e6957d6118b6c3cb39b9217587acc1de8616181aeccf6eb1af2b218ffb60e0d"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:20b9b71a87e94e82d2e3a54e9329af49bce93d61211e4169cfe7b490972cf8d0"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:87ac8b80901a84653a9b4e45a4d71fd0961da607b386df2d6bcb0fa13208cadc"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:9d76792ba9869eb96ba3b41b0bfb48c6adfaa58a361bba6083505c84c5a8d61e"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/buildpack-procfile@sha256:1995d5e70d12b928172a09b11ab7b0c07da7857588e743b0e55d4be0d1a59fbf"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:7c9764d4c30c038ab52e10075a9ac3d05b17be28679eb2c3309156be8a0ef84a"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:995e2898a7a7fe1cb38ac24263d2f7d3fba1051ce170033320116a8aa81f9b21"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:dcf51d14112e5b97cf2f7e1cd19dd89e4850762080dc29c80623c02413ca6e6f"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.8.4"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "3.0.3"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "3.0.3"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "4.1.0"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "2.1.3"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "3.0.3"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "4.1.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "4.1.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.2.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.1.2"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true
