description = "Ubuntu 24.04 AMD64+ARM64 base image with buildpacks for .NET, Go, Java, Node.js, PHP, Python, Ruby & Scala."

[stack]
id = "heroku-24"
build-image = "docker.io/heroku/heroku:24-build"
run-image = "docker.io/heroku/heroku:24"
run-image-mirrors = ["public.ecr.aws/heroku/heroku:24"]

[lifecycle]
version = "0.20.1"

[build]
image = "docker.io/heroku/heroku:24-build"

[run]
[[run.images]]
image = "docker.io/heroku/heroku:24"
mirrors = ["public.ecr.aws/heroku/heroku:24"]

[[buildpacks]]
  id = "heroku/dotnet"
  uri = "docker://docker.io/heroku/buildpack-dotnet@sha256:68c5f8de21a5da2df5b186d3a43d5b5481eacc4de786bf1e5bb15e5b6c3c4477"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:0600278cc2f7d8c8162fbac034a1533bab26407da3a7da9e7e953bcfd71bce3a"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:a553ae4d8f8dd564599991959020961e7f8881e575169bcaf3a6bbcac697b943"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:f6fc41acaae63c8bf935e1e52d4d0e5f18481f19834fd01f3e4b89be93e13054"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:21c6e7c49c6a62167ff1f8c2d1aaebdde99e278d677ecb04ec404a1f66065d93"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/buildpack-procfile@sha256:2e57b342cab83f6517bb1b94f7ebedd2f9b723b8dc7536c15009a779ef2df92f"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:e2ec6cad5e8bf61ea0a0babc02bd01bdc7471650a04555d9d6ab785190a279ec"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:b98b873adf2fc51dce9ae09331486cfe2f799ec233eb7128d1f5068e6e63e25a"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:3a898ab1beb3eecc3f5e2bdbbdefe086e83108c918d2942011486042db8aaded"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.18.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "3.2.14"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "3.2.14"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "6.0.2"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "3.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "3.2.14"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "6.0.2"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "6.0.2"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.4.4"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.2.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/dotnet"
    version = "0.1.3"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true
