description = "Ubuntu 24.04 AMD64+ARM64 base image with buildpacks for .NET, Go, Java, Node.js, PHP, Python, Ruby & Scala."

[stack]
id = "heroku-24"
build-image = "docker.io/heroku/heroku:24-build"
run-image = "docker.io/heroku/heroku:24"
run-image-mirrors = ["public.ecr.aws/heroku/heroku:24"]

[lifecycle]
version = "0.20.1"

[build]
image = "docker.io/heroku/heroku:24-build"

[run]
[[run.images]]
image = "docker.io/heroku/heroku:24"
mirrors = ["public.ecr.aws/heroku/heroku:24"]

[[buildpacks]]
  id = "heroku/dotnet"
  uri = "docker://docker.io/heroku/buildpack-dotnet@sha256:0ff6cbece898f615c70e129058f8ef88c94fea8ed2f5cf210606ce5ed924d171"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:0600278cc2f7d8c8162fbac034a1533bab26407da3a7da9e7e953bcfd71bce3a"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:1f4a73ee32f6277e936943b5871e7724c70c8221947437e63c2042f547c19c67"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:74ad6a8c25014b19d6eac5619f3f80f8c6121c6067706182c16390e729b5d6be"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:21c6e7c49c6a62167ff1f8c2d1aaebdde99e278d677ecb04ec404a1f66065d93"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/buildpack-procfile@sha256:2e57b342cab83f6517bb1b94f7ebedd2f9b723b8dc7536c15009a779ef2df92f"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:c2b071f00e456f5914e273e12cbc4bb35baf9d3c08b06d86bc7e585c0581baf6"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:b98b873adf2fc51dce9ae09331486cfe2f799ec233eb7128d1f5068e6e63e25a"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:bde371a17cd1d1785d721554eba4dddc7a9646aba3c60e18ba853b13fd5734b9"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.17.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "3.2.13"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "3.2.13"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "6.0.1"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "3.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "3.2.13"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "6.0.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "6.0.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.4.4"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.2.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/dotnet"
    version = "0.1.2"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.2"
    optional = true
