description = "Heroku-24 (Ubuntu 24.04) base image with buildpacks that support amd and arm architectures"

[stack]
id = "heroku-24"
build-image = "heroku/heroku:24-build"
run-image = "heroku/heroku:24"

[lifecycle]
version = "0.19.6"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:96a7654a536e5fcc4f09a80424a7f3bab40e61a97a0d98599ca7becb1e9400b7"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:60223d932e6e425f89606e9cbe23c69dc1047ccbbe6480cb5d11a8f43677ebd5"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/buildpack-procfile@sha256:2de0917544af55f26631a5a9e3f812b1da6c05067abfd75dc9a87a1da7172586"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:a64c75016e01aced71f98262eba7cdd132170f43df5281c94d624cbb1d230da2"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:b98b873adf2fc51dce9ae09331486cfe2f799ec233eb7128d1f5068e6e63e25a"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.10.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "3.2.2"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "3.2.2"
    optional = true
  # TODO: Enable once `heroku/jvm` supports Heroku-24.
  # [[order.group]]
  #   id = "heroku/jvm"
  #   version = "TBD"
  #   optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "3.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "3.2.2"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.3.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true
