description = "Base builder for Heroku-18 stack, based on ubuntu:18.04 base image"

[stack]
id = "heroku-18"
build-image = "heroku/heroku:18-cnb-build"
run-image = "heroku/heroku:18-cnb"

[lifecycle]
version = "0.16.1"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-buildpack@sha256:21990393c93927b16f76c303ae007ea7e95502d52b0317ca773d4cd51e7a5682"

[[buildpacks]]
  id = "heroku/scala"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/scala-v96?id=heroku/scala&name=Scala&version=0.0.0&stacks=heroku-18"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-function-buildpack@sha256:b4750feb3b738786cdbee31146ea9bfb2b63ab124dca2f1605c2ec79ab11e05c"

[[buildpacks]]
  id = "heroku/gradle"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/gradle-v39?id=heroku/gradle&name=Gradle&version=0.0.0&stacks=heroku-18"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/ruby-v271?id=heroku/ruby&name=Ruby&version=0.0.0&stacks=heroku-18"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:2.0.0"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python-v232?id=heroku/python&name=Python&version=0.0.0&stacks=heroku-18"

[[buildpacks]]
  id = "heroku/php"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php-v230?id=heroku/php&name=PHP&version=0.0.0&stacks=heroku-18"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go-v173?id=heroku/go&name=Go&version=0.0.0&stacks=heroku-18"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-buildpack@sha256:e124fd4dcd60460ab8588c1ce0fc07fb07b84b4100d6f03d34daa2ffea097ce8"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-function-buildpack@sha256:467a2fdab78b22f05f6f0d6801ccad0a2cc1c963838df311e1a237aec2bfdc71"

[[order]]
  [[order.group]]
    id = "heroku/ruby"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "0.10.4"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "0.3.43"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.6.4"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "0.6.9"

# heroku/java previously supported Gradle by mixing in the shimmed heroku/gradle buildpack. When we decided to make a
# clean cut and not have shimmed buildpacks in the CNB repository, support for Gradle in heroku/java was dropped.
# To maintain backwards compatibilty, we have this order definition here that mirrors what was in heroku/java
# previously. It can be removed when the heroku/java CNB supports Gradle again.
[[order]]
  [[order.group]]
    id = "heroku/jvm"
    version = "1.0.9"

  [[order.group]]
    id = "heroku/gradle"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true
