description = "Internal builder image for Salesforce Functions."

[stack]
id = "heroku-22"
build-image = "heroku/heroku:22-cnb-build"
run-image = "heroku/heroku:22-cnb"

[lifecycle]
# We have to use an older lifecycle version in this builder image since lifecycle 0.18.0
# dropped support for Buildpack API versions <0.7, and we know of at least one custom CNB
# used by Functions customers that's using a legacy Buildpack API version:
# https://github.com/CSGAMERSServices/puppeteer-heroku-buildpack
version = "0.17.6"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://docker.io/heroku/buildpack-java-function@sha256:6895461f4775acd6bfbd05d6f72662ba2fd91e295d75fd0c33759bb417115552"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://docker.io/heroku/buildpack-nodejs-function@sha256:e42e57b3431e348a88f696ef830d6aa39ec71ee4c04adad6141b9a5c5533de12"

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "3.4.3"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "6.0.4"
