description = "Internal builder image for Salesforce Functions"

[stack]
id = "heroku-22"
build-image = "heroku/heroku:22-cnb-build"
run-image = "heroku/heroku:22-cnb"

[lifecycle]
version = "0.17.2"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://docker.io/heroku/buildpack-java-function@sha256:56df8e921781f621b6a57515ffa207c684f73e2f222f7fa3ed64d23a1f22aba6"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://docker.io/heroku/buildpack-nodejs-function@sha256:54fc783e1481fd8d3d5289ee67349f240a3421e6d4d239eb3f396659133e8ff6"

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "1.1.7"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "3.2.2"
