description = "Internal builder image for Salesforce Functions."

[stack]
id = "heroku-22"
build-image = "heroku/heroku:22-cnb-build"
run-image = "heroku/heroku:22-cnb"

[lifecycle]
# We have to use an older lifecycle version in this builder image since lifecycle 0.18.0
# dropped support for Buildpack API versions <0.7, and we know of at least one custom CNB
# used by Functions customers that's using a legacy Buildpack API version:
# https://github.com/CSGAMERSServices/puppeteer-heroku-buildpack
version = "0.17.6"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://docker.io/heroku/buildpack-java-function@sha256:769aea054da53e6edcdb40787e056609a2f5eb70ffc1bd8abffaa7c0ca3c68af"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://docker.io/heroku/buildpack-nodejs-function@sha256:d72fdfc93e49f74eca8376584f01fdc1a9cbcaf35049e006aaaae412622c9f84"

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "3.2.4"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "6.0.0"
