description = "Internal builder image for Salesforce Functions."

[stack]
id = "heroku-22"
build-image = "heroku/heroku:22-cnb-build"
run-image = "heroku/heroku:22-cnb"

[lifecycle]
# We have to use an older lifecycle version in this builder image since lifecycle 0.18.0
# dropped support for Buildpack API versions <0.7, and we know of at least one custom CNB
# used by Functions customers that's using a legacy Buildpack API version:
# https://github.com/CSGAMERSServices/puppeteer-heroku-buildpack
version = "0.17.6"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://docker.io/heroku/buildpack-java-function@sha256:f327b60a6ea0521eb0c6f6efc75443da806ded1433250a0883f7370063dc2680"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://docker.io/heroku/buildpack-nodejs-function@sha256:4ca345dd6d32bf5e9bcb092e9697522096a788bd7590ab76297a0f7c7bcc45c9"

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "3.0.6"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "4.1.1"
