description = "Base builder for Heroku-22 stack, based on ubuntu:22.04 base image"

[stack]
id = "heroku-22"
build-image = "heroku/heroku:22-cnb-build"
run-image = "heroku/heroku:22-cnb"

[lifecycle]
version = "0.16.1"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:811742ee6797aea310d0bd7430860c7ed4fec8a2f4bc29c3a359460adf4bcb8a"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:94a5360759d28b86415a5c8e7f4602591154b97d51573eb3d353d84397c35602"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://docker.io/heroku/buildpack-nodejs-function@sha256:16e6581b4769f0425a6f502dad4ed12b1d5d63bd44340310ca7829290d700210"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:7e4a2bc5f80e6892949117e3ae48ecac0b54760058999c48a5907a56268949fe"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://docker.io/heroku/buildpack-java-function@sha256:5025f31347af8d3642701ab416c3f1c5278775538f2d8e3d82ed1e03ea3de533"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:5210d085d5b39e196fe7e0f8463fb06f96dc2e007ae985e11e92059a1e3b1183"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:bba64106cf47ded595dae478a3b26cd36756417efa96d01941de0b22519c60c9"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:fd32f123fdfa3e94eeb4ce2ad82aad353f6a3b87ac70bfebfdd30cc41927a737"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:19e44139b850b3b9040f21d436ec693f0dff82e931bbff500e9876f4febacd0e"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:2.0.0"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.5.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "1.1.4"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "1.1.4"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "3.0.0"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "2.0.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "1.1.4"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "1.1.4"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "3.0.0"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "3.0.0"

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "3.0.0"

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.1.8"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.1.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true
