description = "Base builder for Heroku-22 stack, based on ubuntu:22.04 base image"

[stack]
id = "heroku-22"
build-image = "heroku/heroku:22-cnb-build"
run-image = "heroku/heroku:22-cnb"

[lifecycle]
version = "0.16.1"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:8d48c06778522af428da5511d00763ceea792ca0fc4700c8628e6072c5f43f3f"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:370b3b537642fa35553298ea61119e85fd1ecd6153009611a2fc4d784b26fb92"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://docker.io/heroku/buildpack-nodejs-function@sha256:f338c522db5645afc69c269df479ec622cb0ece5d7b5bdb1b96e696393f2e76b"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:d17e24702dcc831c4988d846dcc18d4fa815a99565f6aa8cb3b013ce0a5bc085"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://docker.io/heroku/buildpack-java-function@sha256:78e88ee7996c27843f0d37273bab5623dea0ed2d147d61c33e330c96668b6581"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:dd41aacd9ce11a11fdc3f0ba0bf4cd8a816fc56c634d30c2806998b5fce9534d"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:cecab9a786d4906af64ee09213c774c0bd43471f8361101ae901ba30a6b41fce"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:7f48a442c056cd19ea48462e05faa2837ac3a13732c47616d20f11f8c847a8c4"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:2.0.0"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.4.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "0.8.24"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "0.4.4"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "1.1.1"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "2.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "0.10.7"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.6.7"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "1.1.1"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "1.1.1"

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "1.1.1"

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.1.4"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true
