description = "Base builder for Heroku-22 stack, based on ubuntu:22.04 base image"

[stack]
id = "heroku-22"
build-image = "heroku/heroku:22-cnb-build"
run-image = "heroku/heroku:22-cnb"

[lifecycle]
version = "0.14.1"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-buildpack@sha256:0db9f907a0f340fd659a0609f4f65fa3f7239d5525c00633818f4df6bdefa57b"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-function-buildpack@sha256:c9e3e0b7e46a3b3cba26ad5c50ce2a89ff0a030926557cb39647dc504de04c18"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-buildpack@sha256:e3031bc05816379243c5f732e4acb4345f7c968977b91bae0e40dd954894b87e"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-function-buildpack@sha256:f97f45a9c605435547411479c61d2def2a92a42e5015e8356db431e18776cd1a"

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "0.9.7"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.5.6"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "0.3.32"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "0.6.0"
