description = "Base builder for Heroku-22 stack, based on ubuntu:22.04 base image"

[stack]
id = "heroku-22"
build-image = "heroku/heroku:22-cnb-build"
run-image = "heroku/heroku:22-cnb"

[lifecycle]
version = "0.14.1"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-buildpack@sha256:7dd9dcbe42490e5e69a483b973666fd5df16790f634053b01a333044f0c4af8c"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-function-buildpack@sha256:65607e9920944f16fbe7c49110f17a856cb96dde0c0148484f4db896c4488aa8"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-buildpack@sha256:b5fb470e12507e2a2dfa48e74648bd8e9c6adc5ae70e6145fb3871d782a8e2bb"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-function-buildpack@sha256:46e353cadcd941baeb0f566d7ab7b1f13c18e96223c1143dc51b258638ab9d47"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:fdc270c4414dc636daf29e269a67f28bb1a8c4aee89974d80b90edbdc10ae8a2"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:2.0.0"

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "0.9.15"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.5.11"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "0.3.38"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "0.6.5"

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.1.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true
