description = "Ubuntu 22.04 AMD64 base image with buildpacks for Go, Java, Node.js, PHP, Python, Ruby & Scala."

[stack]
id = "heroku-22"
build-image = "heroku/heroku:22-cnb-build"
run-image = "heroku/heroku:22-cnb"

[lifecycle]
version = "0.19.7"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:1bbd4e89e4245b4c74d4edd264dbde73975d191d13fcd6d05b45d1bbd2de6e41"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:7c5e64be14b9118831b37f9321f3a04d386a3df92d486ccb7477c8a663490f4d"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:2fd25d8868db7b4d95ef45f173dc33843e737bfe67938212cdab81af67f87dfd"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:21c6e7c49c6a62167ff1f8c2d1aaebdde99e278d677ecb04ec404a1f66065d93"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/buildpack-procfile@sha256:2de0917544af55f26631a5a9e3f812b1da6c05067abfd75dc9a87a1da7172586"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:9b7f89ecd5cec812be0f7f4109d2f98fd78c9138ff755b6be3e8a50ff591e776"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:b98b873adf2fc51dce9ae09331486cfe2f799ec233eb7128d1f5068e6e63e25a"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:0c50dda170abd417da3aadde8dd7be5f1e724f6b87137a730e946d814c6b9e92"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.11.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "3.2.4"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "3.2.4"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "6.0.0"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "3.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "3.2.4"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "6.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "6.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.4.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.2.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.1.1"
    optional = true
