description = "Base builder for Heroku-22 stack, based on ubuntu:22.04 base image"

[stack]
id = "heroku-22"
build-image = "heroku/heroku:22-cnb-build"
run-image = "heroku/heroku:22-cnb"

[lifecycle]
version = "0.17.1"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:4639874ee2ae74c6250962827433dfb7023082bef39e678c593678ff00d57673"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:3b69171e416c8062b3caefc97c206cd006a197773e380d09cb7f704a10147dee"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:16882adf3fc2c3c5cac48162ca6e5ae8f1af6c5b4e18d518c6cc97aaa4ca8fd7"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:19e44139b850b3b9040f21d436ec693f0dff82e931bbff500e9876f4febacd0e"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb@sha256:ea7219d4bb50196b4f292c9aae397b17255c59a243d7408535d2a03a5cd2b040"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:4bc48b1ce0f6fec47eafffe0be86ec74638575fbafba2616165921e661561613"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:c4f5df18845ebd3a72be17699de63ec9afb784915fe357a8a30854d0dc61631d"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:14169e0dd1531b00f3d423787618425f1739af02ba21a9a6d88c4bc7024574cb"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.7.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "1.1.7"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "1.1.7"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "3.2.0"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "2.1.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "1.1.7"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "3.2.0"

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "3.2.0"

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.1.10"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.1.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true
