description = "Base builder for Heroku-22 stack, based on ubuntu:22.04 base image"

[stack]
id = "heroku-22"
build-image = "heroku/heroku:22-cnb-build"
run-image = "heroku/heroku:22-cnb"

[lifecycle]
version = "0.16.1"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:811742ee6797aea310d0bd7430860c7ed4fec8a2f4bc29c3a359460adf4bcb8a"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:e5519335d777a818929aa2050b4a8d0b73e9d31f3593779732631b3cf4c08f34"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://docker.io/heroku/buildpack-nodejs-function@sha256:970b6202d65feeb8e1d090af242da2e9e1dd10c48b23664ec25aab10d3d7038a"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:a5a946975e79d73d0a0f801aa3b8cc4e3de69a092eb588aa69e8c7d2552bc581"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://docker.io/heroku/buildpack-java-function@sha256:bada76191f6092a536b734bb35019f4695841656d275dffce6f9e72df28cda26"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:b39387744fd45eb9042e82cd0071c19e103fafb0409c1b77dc7563adb691c776"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:1c7eec24cbce0570394d671991886be199950f85ec2c497314af2f1755be3b52"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:fd32f123fdfa3e94eeb4ce2ad82aad353f6a3b87ac70bfebfdd30cc41927a737"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:19e44139b850b3b9040f21d436ec693f0dff82e931bbff500e9876f4febacd0e"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:2.0.0"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.5.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "1.1.3"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "1.1.3"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "2.0.0"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "2.0.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "1.1.3"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "1.1.3"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "2.0.0"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "2.0.0"

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "2.0.0"

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.1.6"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.1.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true
