description = "Base builder for Heroku-22 stack, based on ubuntu:22.04 base image"

[stack]
id = "heroku-22"
build-image = "heroku/heroku:22-cnb-build"
run-image = "heroku/heroku:22-cnb"

[lifecycle]
version = "0.16.1"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:1de82e4c18f6240fb9199446ece743435a4233c560a1900300887f004d83ddbf"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-buildpack@sha256:25f22a506c1b8fbad0dcd4232d96f1e8dd3194c4b9ece6ce61b56cf0a494958f"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-function-buildpack@sha256:8402c9b463dd7042b0f09bb89bd181f5b40db6ab07fd2838cc9a629767e9c1fd"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-buildpack@sha256:21990393c93927b16f76c303ae007ea7e95502d52b0317ca773d4cd51e7a5682"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-function-buildpack@sha256:b4750feb3b738786cdbee31146ea9bfb2b63ab124dca2f1605c2ec79ab11e05c"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:043cd538baa5f1414ac58871a32c41c5017bc4ab4c694ceb73ea10138338a4de"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:7f48a442c056cd19ea48462e05faa2837ac3a13732c47616d20f11f8c847a8c4"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:2.0.0"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.3.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "0.8.20"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "0.4.1"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "1.0.9"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "2.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "0.10.3"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.6.3"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "0.3.43"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "0.6.9"

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.1.3"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true
