description = "Base builder for Heroku-22 stack, based on ubuntu:22.04 base image"

[stack]
id = "heroku-22"
build-image = "heroku/heroku:22-cnb-build"
run-image = "heroku/heroku:22-cnb"

[lifecycle]
version = "0.15.3"

[[buildpacks]]
  id = "heroku/python-functions-experimental"
  uri = "https://heroku-buildpack-python.s3.us-east-1.amazonaws.com/cnb/python-functions-experimental-0.1.0.cnb"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-buildpack@sha256:9fbb01c032b830382928f4ed36355eccf2743b578fe74c86dde3b700afc90d37"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-function-buildpack@sha256:113b0db275b05a2a33279300cd4a350d2def0650d45ca38274302d2bbd60855d"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-buildpack@sha256:3de6f9431995a029deaa6bcec60b7c539eb6f2cefbaf82a740e8c1117431390b"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-function-buildpack@sha256:561e43d17423da8ada570f7cabbf03824cfe36e77a9f74542fe41a468480d068"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:be8222c2ba29871324f79e4e2aa0d3d1990c310f0e12c8ea296507ffac7d7705"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:7f48a442c056cd19ea48462e05faa2837ac3a13732c47616d20f11f8c847a8c4"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:2.0.0"

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "0.8.15"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "0.3.2"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "1.0.6"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "2.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python-functions-experimental"
    version = "0.1.0"

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "0.9.18"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.5.14"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "0.3.40"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "0.6.6"

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.1.2"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true
