api = "0.2"

[buildpack]
id = "evergreen/fn"
version = "0.1"
name = "Evergreen Function"

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "0.4.3"

  [[order.group]]
    id = "heroku/nodejs-npm"
    version = "0.2.0"

  [[order.group]]
    id = "io.projectriff.node"
    version = "0.3.1-BUILD-SNAPSHOT"

  [[order.group]]
    id = "salesforce/nodejs-fn"
    version = "1.5.1"
