api = "0.2"

[buildpack]
id = "evergreen/fn"
version = "0.3.0"
name = "Evergreen Function"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.3.0"

  [[order.group]]
    id = "projectriff/streaming-http-adapter"
    version = "1.4.0"

  [[order.group]]
    id = "projectriff/node-function"
    version = "1.5.0"

  [[order.group]]
    id = "salesforce/nodejs-fn"
    version = "2.0.6"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "0.3.2"
