description = "[DEPRECATED] Heroku-20 (Ubuntu 20.04) base image with a mixture of shimmed classic Heroku buildpacks and native CNBs. Use 'heroku/builder' instead."

[stack]
id = "heroku-20"
build-image = "heroku/heroku:20-cnb-build"
run-image = "heroku/heroku:20-cnb"

[lifecycle]
# We have to use an older lifecycle version in this builder image since lifecycle 0.18.0
# dropped support for Buildpack API versions <0.7, and cnb-shim is currently using v0.4:
# https://github.com/heroku/cnb-shim/issues/69
version = "0.17.5"

[[buildpacks]]
  id = "heroku/builder-eol-warning"
  uri = "./end-of-life-buildpack/"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.0.0&name=Heroku+Go+(Shimmed)"

[[buildpacks]]
  id = "heroku/gradle"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/gradle?version=0.0.0&name=Heroku+Gradle+(Shimmed)"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:20b9b71a87e94e82d2e3a54e9329af49bce93d61211e4169cfe7b490972cf8d0"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:643a4e4b95099b80f42e06fbdbbfb54b79c53989109510990a6085e41dd3862e"

[[buildpacks]]
  id = "heroku/php"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php?version=0.0.0&name=Heroku+PHP+(Shimmed)"

# We have to use Procfile CNB v2.0.2 in this builder image, since cnb-shim isn't compatible with
# the direct process mode used in newer Procfile CNB:
# https://github.com/heroku/cnb-shim/issues/74
[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/buildpack-procfile@sha256:2549eee29b64c5dc063a3966c65baf1f264389645f54d416a320aa9e20b09592"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.0.0&name=Heroku+Python+(Shimmed)"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/ruby?version=0.0.0&name=Heroku+Ruby+(Shimmed)"

[[buildpacks]]
  id = "heroku/scala"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/scala?version=0.0.0&name=Heroku+Scala+(Shimmed)"

[[order]]
  [[order.group]]
    id = "heroku/ruby"
    version = "0.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true
  [[order.group]]
    id = "heroku/builder-eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true
  [[order.group]]
    id = "heroku/builder-eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "0.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true
  [[order.group]]
    id = "heroku/builder-eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true
  [[order.group]]
    id = "heroku/builder-eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true
  [[order.group]]
    id = "heroku/builder-eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "3.0.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true
  [[order.group]]
    id = "heroku/builder-eol-warning"
    version = "1.0.0"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "4.1.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true
  [[order.group]]
    id = "heroku/builder-eol-warning"
    version = "1.0.0"
