description = "Base builder for Heroku-20 stack, based on ubuntu:20.04 base image"

[stack]
id = "heroku-20"
build-image = "heroku/heroku:20-cnb-build"
run-image = "heroku/heroku:20-cnb"

[lifecycle]
version = "0.17.2"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.0.0&name=Heroku+Go+(Shimmed)"

[[buildpacks]]
  id = "heroku/gradle"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/gradle?version=0.0.0&name=Heroku+Gradle+(Shimmed)"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:a031701917cf111b0122a20d6f987adc88dfc7d8e0fe8d8183e615634fa7f0fe"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:16882adf3fc2c3c5cac48162ca6e5ae8f1af6c5b4e18d518c6cc97aaa4ca8fd7"

[[buildpacks]]
  id = "heroku/php"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php?version=0.0.0&name=Heroku+PHP+(Shimmed)"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb@sha256:2549eee29b64c5dc063a3966c65baf1f264389645f54d416a320aa9e20b09592"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.0.0&name=Heroku+Python+(Shimmed)"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/ruby?version=0.0.0&name=Heroku+Ruby+(Shimmed)"

[[buildpacks]]
  id = "heroku/scala"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/scala?version=0.0.0&name=Heroku+Scala+(Shimmed)"

[[order]]
  [[order.group]]
    id = "heroku/ruby"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "1.1.7"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "3.2.1"
